In [1]:
# Problem 2
'''in an e-commerce company, the management wants to predict whether a customer will purchase a high value product 
 based on their age ,time spent on the website ,and whether they have added items to their cart. the goal is to optimize 
 marketing strategies by targeting potential customers more effectively ,there increasing sales and revenue . '''

'in an e-commerce company, the management wants to predict whether a customer will purchase a high value product \n based on their age ,time spent on the website ,and whether they have added items to their cart. the goal is to optimize \n marketing strategies by targeting potential customers more effectively ,there increasing sales and revenue . '

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
X= np.array([[25,30,0],[30,40,1],[20,35,0],[32,46,1]]) # [age,time_spend,add_cart or not)
Y=np.array([0,1,0,1])
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size = .2, random_state=42)

In [4]:
print(X)

[[25 30  0]
 [30 40  1]
 [20 35  0]
 [32 46  1]]


In [5]:
model=LogisticRegression()
model.fit(X_train,Y_train)
accuracy= model.score(X_test,Y_test)
print(f'Model accuracy : {accuracy}')

Model accuracy : 1.0


In [ ]:
user_age= float(input("Enter your custumer age: "))
user_time_spent=float(input("Enter the time spent on website :"))
user_added_to_cart=int(input("Enter 1 if added to cart other wise \n enter 0 :"))
user_data = np.array([[user_age,user_time_spent,user_added_to_cart ]])
prediction = model.predict(user_data)
if prediction[0] == 1:
    print("The customer is likely to purchase")
else:
    print("The customer not likely to purchase")
    
